import Head from 'next/head';
import Image from 'next/image';
import Footer from '../components/Footer';
import Intro from '../components/Intro';
import Navbar from '../components/Navbar';
import Services from '../components/Services';
import { data } from '../data';
import styles from '../styles/Home.module.css';

export default function Home({services}) {
	
	return (
		<div>
			<Head>
				<title>Master</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Intro />
			<Services services={services} />
		</div>
	);
}

export const getStaticProps = async () => {
	const services = data;
	return {
		props:{
			services
		},
	};
};
